version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: clinical_trials
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d

  airflow:
    image: apache/airflow:2.7.1
    container_name: airflow
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/clinical_trials
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dag
      PYTHONPATH: /opt/airflow
    volumes:
      - ./flow/dag:/opt/airflow/dag
      - ./flow/src:/opt/airflow/src
      - ./airflow_logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      airflow webserver
      "

  airflow-scheduler:
    image: apache/airflow:2.7.1
    container_name: airflow-scheduler
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/clinical_trials
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dag
      PYTHONPATH: /opt/airflow
    volumes:
      - ./flow/dag:/opt/airflow/dag
      - ./flow/src:/opt/airflow/src
      - ./airflow_logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    command: >
      bash -c "
      airflow db migrate &&
      airflow scheduler
      "

volumes:
  postgres_data:
  airflow_logs: