version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: clinical_trials
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d clinical_trials"]
      interval: 5s
      timeout: 3s
      retries: 10


  airflow:
    image: apache/airflow:2.7.1
    container_name: airflow
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/clinical_trials
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dag
      PYTHONPATH: /opt/airflow
    volumes:
      - ./flow/dag:/opt/airflow/dag
      - ./flow/src:/opt/airflow/src
      - ./airflow_logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    command: >
      bash -c "
      pip install --no-cache-dir dbt-postgres==1.7.9 &&
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      airflow webserver
      "
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health || exit 1"]
      interval: 10s
      retries: 10


  airflow-scheduler:
    image: apache/airflow:2.7.1
    container_name: airflow-scheduler
    depends_on:
      airflow:
        condition: service_healthy
    ports:
      - "1234:1234"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/clinical_trials
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dag
      PYTHONPATH: /opt/airflow
    volumes:
      - ./flow/dag:/opt/airflow/dag
      - ./flow/src:/opt/airflow/src
      - ./airflow_logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    command: >
      bash -c "
      pip install --no-cache-dir dbt-postgres==1.7.9 &&
      airflow scheduler &&
      sleep 15 &&
      airflow dags trigger clinical_trials_pipeline
      "


volumes:
  postgres_data:
  airflow_logs: